Fix custom labels when dataset has timeholes
If a custom label is added in a graph which has holes in the data collection
we get an error:
Creating graphs: Traceback (most recent call last):
  File "./pcp2pdf", line 161, in <module>
    pcpstats.output(output_file=opts.output_file)
  File "/home/michele/Devel/pcp/src/pcp2pdf/pcp2pdf_stats.py", line 631, in output
    if self.create_graph(fname, label, metrics):
  File "/home/michele/Devel/pcp/src/pcp2pdf/pcp2pdf_stats.py", line 495, in create_graph
    self.find_max(self.labels[label], metrics)), xycoords='data',
  File "/home/michele/Devel/pcp/src/pcp2pdf/pcp2pdf_stats.py", line 273, in find_max
    x2 = mdates.date2num(timestamps[time_key_right])
IndexError: list index out of range
Example: pcp2pdf --output skipped.pdf  -t "4 minute"  -l 'foo:2014-05-30 16:30:00' -a skipped.0